title: MPV Anime Build v1.3
description: Automated High-Quality Upscaling for Anime & Live Action
theme: jekyll-theme-slate

# This ensures your Google Verification stays active with the theme
google_site_verification: -b34UEuV_TSu0alUSUY-xI03FbCL1JBURzYQMp7uT7Q

# Optional: Add your GitHub username here
github:Chinna95P
  is_project_page: true