title: "MPV Anime Build v1.3"
description: "Automated High-Quality Upscaling for Anime & Live Action"
theme: jekyll-theme-slate

# QUOTES ADDED BELOW to fix the YAML error:
google_site_verification: "-b34UEuV_TSu0alUSUY-xI03FbCL1JBURzYQMp7uT7Q"

github:Chinna95P
  is_project_page: true